### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by StuAalto** [mwfoekens/Probot#1]
Hello.
I attended your presentation of Probot during the monthly open space of the Robot Framework community on Friday 30 June.
First of all, well done.
 It's not really a problem but rather a request concerning the ppt presentation of your project and the architecture of the tool that you showed.
Would you be able to make it available in the repository?

**Comment by mwfoekens** [comment]
Definitely! Will upload the presentation containing the design images in the week of July 10 2023!

**Comment by mwfoekens** [comment]
Added the presentation to the repo.
